### ISSUE TITLE
Create new Top App Bar component, using @material/top-app-bar

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web-react#11]
- [ ] New React.Component which returns the HTML structure for top app bar
- [ ] Include the Sass files from @material/top-app-bar
- [ ] Props on the component should map to the variants of top-app-bar (short, short-collapsed)
- [ ] Include the foundation file from @material/top-app-bar
- [ ] Wire together all synthetic React events top app bar needs to listen to
- [ ] Update the components state, and trigger a React re-render, as necessary
- [ ] Screenshot test to cover all properties
- [ ] JS test to cover all React code

**Comment by moog16** [comment]
fixed by #13
