### ISSUE TITLE
Convert to one package

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#139]
- [ ] update webpack to build one package
- [ ] remove all package.json and .npmignore files from each individual package
- [ ] update packages to use relative paths instead of @material/react-foo packages
- [ ] update how to install documentation
- [ ] create a root index.js to export all packages

**Comment by kfranqueiro** [comment]
This topic has come up recently for core as well but I would like to consider what we're gaining out of this vs. losing before jumping to conclusions and doing it.

In the case of MDC React in particular though, I'm curious which method of consumption is more common / preferable.

**Comment by kraenhansen** [comment]
I think its important to make a distinction between how a projects source-code is structured and how it's distributed. A mono-repository can make sense from a maintainability point of view, as you wont have to make releases of a core library before adopting changes (that might result in new requirements on the core library) but that is different from the method of distribution.

On the topic of which method of consumption is more common / preferable I would definitely advocate for separate packages for each framework (React, Vue, Angular, etc.) - if you are not distributing separate packages for each component it would also be preferable if there existed a way / guide to avoid bundling in components that my app is not actively using (perhaps by some sort of configuration or automatic dead-code removal).

**Comment by lynnjepsen** [comment]
Given that both [React Toolbox](https://www.npmjs.com/package/react-toolbox) and [Material UI](https://www.npmjs.com/package/material-ui), both very popular React component libraries, serve their components as one package...I think we should update MDC React to one package as well.

This does not necessarily mean MDC Web needs to update to one package. We can make this change only in MDC React, and then do more investigation for MDC Web.

**Comment by kfranqueiro** [comment]
[RMWC](https://github.com/jamesmfriedman/rmwc) is also a single package, so I suppose there's that. I might put more weight in that than the others since RMWC is also wrapping MDC Web. :)

**Comment by kfranqueiro** [comment]
I'd still like to know what problem we're actually solving by doing this, though?

One thing I'd point out is that this makes it impossible to do partial upgrades as MDC React works towards updating to a new MDC Web release. In other words you can't e.g. update just text field and deal with breaking changes there in isolation from updating everything else at the same time. I'm pretty sure that was something that was taken advantage of in a previous upgrade process.

**Comment by lynnjepsen** [comment]
Somewhat related, because webpack.config.js needs cleaning before we take on this project: #146

**Comment by jamesmfriedman** [comment]
I’ve debated moving to multiple packages but ended up keeping the mono repo for simplicity. 

Webpack 3 / 4 / and roll up all do tree shaking by default so final bundle size is optimized. I know this is cared about since I’ve been alerted by an issue anytime I’ve broken it :)

@kfranqueiro that’s a great point about fixing things in isolation and definitely a valid use case. I’m curious to know how much this comes into play in practice. I personally have never used this pattern but it could be useful as the component library becomes much larger and project using it become much older.

**Comment by rustemgareev** [comment]
As a consumer of MDC React, I just want to point you that installing 20+ separate packages (and updating their versions later) is a huge pain.

```bash
npm i -S @material/react-button @material/react-card @material/react-some-other-component # etc. painful
npm i -S @material/react # much better
```

**Comment by moog16** [comment]
definitely agree - and I'm anticipating having some bandwidth at the end of the quarter since the roadmap doesn't have any new components in December yet.

**Comment by jamesmfriedman** [comment]
Couple of things.

For @rustemgareev 
- You can make this much easier on yourself. Just make bash script that looks something like this with all of the components you need. `update-mdcr.sh`
```
npm i -S \
@material/react-button@latest \
@material/react-card@latest \
@material/react-fab@latest
```
Run like so, or proxy it through a node script.
```
./update-mdcr.sh
```

There is a lot of value in having the individual packages, someday it will save you from the never ending upstream changes.

For @moog16 
I'm assuming you're already using lerna. This is trivial to do, just setup a new directory with whatever you want the mono package called inside of `packages` with its own package.json, and then just add all of the other packages as a dependency. Lerna will do the rest in keeping it up to date. Here mine from RMWC.

https://github.com/jamesmfriedman/rmwc/blob/master/src/rmwc/package.json

**Comment by jamesmfriedman** [comment]
Originally I was on the mono repo train but at this point I would highly recommend keeping the separate packages. While the mono repo was easier to maintain and deploy, every breaking change was miserable to fix for consumers and as you know. MDC contains lots of them.

**Comment by moog16** [comment]
Are you saying that you'd rather fix breaking changes in different PRs? Or in different steps. I'm assuming you fix all breaking changes

**Comment by jamesmfriedman** [comment]
- Version 0.X.0 comes out, breaks buttons, dialogs, and drawers
- Drawers and buttons are easy, but the dialogs are a total rewrite
- For my app, I can just update buttons and drawers, and wait to update dialogs until I have time to go through the entire app and fix them
- Its more for workflow for larger teams than anything. Splitting up the mono-repo has actually allowed the company I work to upgrade our own internal UI library that wraps RMWC more fluidly and not be an all or nothing week long ordeal.
