### ISSUE TITLE
Use MDC Web Typings

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web-react#697]
- [ ] Update MDC Web select (https://github.com/material-components/material-components-web-react/issues/242)
- [x] Update to updated notched outline (https://github.com/material-components/material-components-web-react/issues/560)
- [x] Update list. Breaking changes in 42, 43, and 44 (#740)
- [x] Update checkbox, fab from breaking changes in 0.42.0 https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#0420-2018-12-04
- [x] Update snackbar, button, tab-bar from 0.42.0 changes https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#0430-2019-01-07
- [ ] Update text field from 0.44.0 changes
- [ ] Add Menu to add select
- [x] Update Chips from 0.44.0 changes

Components with breaking changes
- [x] tab-bar
- [x] snackbar
- [x] button
- [x] list
- [x] checkbox
- [x] fab
- [ ] text field
- [ ] select
- [x] notched outline

Other components with no breaking changes
- [x] card
- [x] chips
- [x] dialog
- [x] drawer
- [x] floating-label
- [x] icon-button (@ben-mckernan)
- ~~[ ] layout-grid~~
- [x] line-ripple
- [x] linear-progress
- [x] menu-surface
- [x] radio
- [x] ripple
- [x] switch
- [x] tab
- [x] tab-indicator
- [x] tab-scroller
- [x] top-app-bar
- [x] typography

**Comment by gugu** [comment]
material-icon has no dependency on mdc-web

**Comment by gugu** [comment]
![image](https://user-images.githubusercontent.com/75169/55233034-4f160480-5238-11e9-9a64-25a30a55ebe4.png)
Bundle size before: 1.74 Mb from material-web
![image](https://user-images.githubusercontent.com/75169/55233334-5ab5fb00-5239-11e9-81ee-ce7b5ec6f45a.png)
Current bundle size: 960 kb from material-web and we can save 560 kb more

**Comment by moog16** [comment]
Are you saying by updating to the latest, we're cutting ~70%??

**Comment by gugu** [comment]
Yes. That's why I'm working on it - I want to reduce bundle size

**Comment by gugu** [comment]
But it is mdc-web only, @material/react-* will have the same size

**Comment by moog16** [comment]
Right right - it must be the tree shaking feature that we added in v1. Then hopefully we can get back to the all-in-one package. Also I really appreciate your work on this!

**Comment by gugu** [comment]
Is there anything left with:
1. snackbar, button, tab-bar (I did not find changes)
2.  layout-grid - last released version is v0.41

**Comment by moog16** [comment]
- I think you updated tab-bar already
- and you're right - snackbar was developed during v0.43.0, which is when the breaking change was introduced. 
- this leaves notched-outline, text-field, select (I'm working on it), button (I opened the PR), and icon-button (@ben-mckernan). 

We're looking good to go for releasing in v0.12.0!

**Comment by gugu** [comment]
I'll start text field in this case. Notched outline is changed, but textfield needs to be changed as well to support it correctly

**Comment by moog16** [comment]
correct...text-field will take a bit of time I'm sure. Once that is done, we should update all the other packages @v1 --> v1.1.0 or v1.0.1 (whatever is latest).

**Comment by TroyTae** [comment]
@gugu 
Oh my god, are you already start to update text-field?
If you already working on it, I'll close this PR(https://github.com/material-components/material-components-web-react/pull/812).

**Comment by gugu** [comment]
No, I don't

**Comment by moog16** [comment]
This should have been closed when 0.12.0 was released.
